# Generated by Django 4.2.16 on 2024-11-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('street_number', models.IntegerField()),
                ('street_name', models.TextField()),
                ('apartment_number', models.TextField()),
                ('zip', models.TextField()),
                ('dob', models.DateField()),
                ('registration_date', models.DateField()),
                ('party', models.TextField()),
                ('precinct', models.IntegerField()),
                ('v20state', models.BooleanField()),
                ('v21town', models.BooleanField()),
                ('v21primary', models.BooleanField()),
                ('v22general', models.BooleanField()),
                ('v23town', models.BooleanField()),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
